### ISSUE TITLE
Incentives Meetings Tracking Issue

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#212]
# Meeting Date

Monday, 11th of April, 2022

# Participants

- Martin
- Ben
- Bedeho

# Agenda

- Status of weekly meetings.
- People complaining about not given point in the interim.
- How to deal with unresponsiveness.
- Can't see work submitted.
- We already had one call with council.
- People are confused about budgets.
- Status of Dashboards, CRMs and Forms.

# Postponed Agenda

- Bounty pipeline not working.
- How to get the HR group properly running.
- Go throughs questions on Discord
- How we deal with things when Martin is away.

# Conclusion

## Budgets

Bedeho makes a video, add it ito working group sectino of SYSTEM article.

## Discord

- Organize Participation around FM program and incentices for Ben and Martin
  - tell worker sto ask WG leads
  - weekdays or non-sick daya: every odd hour, Martin checks, every even hour, Ben checks.
  - weekends: twice a day
  - put into Handbook.

## Working Grop Meeting Requests

- A way for leads to get answers.
- Leads can request meetings on-demand open to their workers.
- No incentive for presence.
- Add description of this offering to the Score section of each group, be specific about steps.

## Weekly Council Handover

- Council members only are mandatory, both old and new.
- Held on Zoom.
- Time published a week ahead, ask people what works.
- Is held by Ben & Martin.
- Happens between each council.
- Write a summary of meeting conclusions, anonimized, written by a notetaker on the council. 
- Has to be submitted on forum within 2 days of election completion.
- Is captured in some sort of scoring metric for council.

## Dashboards & Forms

This is current status.

**Live**
- Person Viewer: https://joystream.retool.com/embedded/public/3ef6f2ee-7d4d-4437-b5f6-f59c8cb17ff6?personid=13#
- Person Explorer: https://joystream.retool.com/embedded/public/9478bcc0-f6d6-4f74-bd0a-0637535e75b1
- FM: https://joystream.retool.com/embedded/public/39f655da-9b03-450e-b5c5-f85403dadb82
- Integrator: https://joystream.retool.com/embedded/public/0f4254f1-5402-4f2b-bd29-dce97ac9bf89

**Not Live: but will be in minutes**
- Council Period Viewer: https://joystream.retool.com/embedded/public/668ac0b9-bded-4264-aace-daa541bb5cfd
- Council Explorer: https://joystream.retool.com/embedded/public/ca618c66-8de1-487d-81ab-ce2217c113a7
- Bounty Template: https://joystream.retool.com/embedded/public/1d1d4b17-fb3a-451a-b71f-28e2593c6c0d

# TODO

## Martin 

- Shares new meeting rules and opportunities to relevant parties, and update handbook.
- Updates scoring rules to generate meeting incentives.

## Bedeho

- Bedeho makes a video, add it ito working group sectino of SYSTEM article.

## Ben

- Disable FM filteron Person explorer.
- Add some incentive for integrators generate interactions of persons in CRM who are not yet FMs.
- Add something to hadnbook about past FM program significance and interim period, share back to relevant peope. USeful to add _explainer_, not a only conclusion.
- Remove the constraint form the form which prohibits non-members being introduced as persons.
- Fix dangling links: https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/human-resources-score#crm

**Comment by blrhc** [comment]
# Meeting Date

Thursday, 14th of April, 2022

# Participants

- Ben
- Bedeho

# Agenda

- Considering when Weekly Incentive Meeting should best be held in order to allow us to review previous council period data and set parameters for the next period
- Reviewing some elements of the dashboard and how reward information is being displayed
- Discussing how best to calculate and present the reward data in spreadsheet
- Brief discussion of backups

# Conclusion

## Rhythm of Incentives Tasks

```
# Council 1

## Sat->Sat

Continously performance measure & verify users.

# Transition: Fri/Sat/Sun

Have council handover meeting

# Council 2

## Monday

Final scores for prior network: includes summaries, and publish
  - final scores for network
  - update CRM
  - new FMs

## Tuesday

- Have internal incentives meeting where we determine policy parameters for next period. 
Needs have prepared metrics and proposed policy values for next meeting.
- Publish new policy parameters for next period.
```

- We need to get the spreadsheets for calculating network score and consequent JOY rewards combined into one.
- From now on, induction cap is $15000 and verification cap is $5000

# TODO

## Martin 

- Before every Tuesday meeting, Martin proposes policy variables for (current) round - while there are none for a couple of days the Council should behave as if they were the same as the last round
- Martin must publish and maintain the network performance score/earnings spreadsheet

## Ben

- Need to determine explicit list of metrics to take into each Tuesday meeting, working back from the policy variables, since this is what the meetings are focused on setting, based on the previous results (don't forget referral data etc.)
- Determine which policy variables need to be changed every time (new weights etc. which Martin will propose)
- Get rid of top20 table for non-FMs, and remove idea of new and old JOY
- Show dollar amounts rather than JOY amounts in most places

## Bedeho

- _nothing_

**Comment by blrhc** [comment]
Putting this here as it outlines what needs to be taken into these meetings:

Policy variables which need changing from round-to-round:
```
- Global JOY Budget
- Global tJOY Budget
- USD Subsidy
- Referral JOY Bonus (USD)
- Referrer JOY Bonus (USD)
- Size of Council
- JOY Verification Cap
- JOY FM Induction Cap
- Weighting of Each Working Group in network score calculation
```
Data which will inform these decisions:
```
- Network Score
- Individual WG Scores
- Worker Opportunities Score for Each WG
- Number of Workers Hired and Fired for each group
- Total number of Workers in each WG at end of round and average across period
- Number of new people added to CRM (HR)
- Number of new interactions (HR)
- Number/size of new/total uploads/data objects (storage)
- Total number of spending proposals (council)
- Catastrophic errors will need to be discussed and evaluated when they take place
```

**Comment by bedeho** [comment]
I don't think this is complete or accurate.

How would we update anything about referrals for example? or how to move caps up or down? 
For other numbers I don't see any significance of, such as _the number of spending proposals_, what would we use that for? 

Have you gone through, in detail one by one, and examined how you would adjust each of those policy variables?

**Comment by blrhc** [comment]
# Meeting Date

Thursday, 21st of April, 2022

# Participants

- Ben
- Bedeho
- Martin
- Tomato

# Agenda

- Determining the most significant/urgent problems with the Incentives scheme, and what needs to be done about these problems
- Going over status of todos from last meeting

# Conclusions

- Grading has been severely delayed for a variety of reasons, we agreed to get out the final numbers within a few hours after the meeting ended
- Council handover meetings need to be a lot more focused, particularly on what went wrong on the network over the previous round from the JSG perspective. For example, at the moment it appears that not many groups are submitting working group plans. This needs to be relayed to the Council so that they can communicate it to the working groups.
- For specific issues with working groups, relating to how to use tools etc., calls can be held with the working group, but really the direction should be coming directly from the council
- There is no written down procedure for doing the entire grading process, to be used in situations where some person is not available to grade their usual "department". For example, Martin has some scripts which Ben and Tomato don't know how to use, for extracting the testnet wg earnings and doing spotchecks for storage and distribution. This means it is currently impossible to conduct an entire grading without Martin's input.
- More broadly, beyond the scripts, everyone needs to know how to do each part of the process, to avoid repeating the delays we have already faced, so an operational manual sort of thing would be useful.
- When announcing scoring, the associated score calculation spreadsheet also needs to be published alongside the scores.
- Scores being published is very urgent - without scores and earnings nobody is motivated to do anything.
- As a general principle, we need to hold more meetings with WGs, Council etc.
- From now on we will hold daily Council meetings where every CM will need to be present, the meetings will be held on Discord
- Comment I made above for policy variables, info taken into meetings was quite weak, so needs further development.
- Two agenda items for next time: Discuss how to do rewards outside of roles (off-chain), do we need to pay more tJOY?

CADENCE UPDATED

```
# Council 1

## Sat->Sat

Continously performance measure & verify users.

# Transition: Fri/Sat/Sun

Have council handover meeting

# Council 2

## Monday

Final scores for prior network: includes summaries, and publish
  - final scores for network
  - update CRM
  - new FMs
  
- Have internal incentives meeting where we determine policy parameters for next period. (4PM)
Needs have prepared metrics and proposed policy values for next meeting.
- Publish new policy parameters for next period.

```

# TODO

## Martin 
- Getting the grading numbers out
- Writing guides for scripts used as part of grading process
- Further clarification of "who does what?"
- Using Ben's template spreadsheet to create a format going forward
- Basic agenda for daily council meetings

## Tomato
- Assist Martin with getting the grading numbers out

## Ben
- Assist Martin with getting the grading numbers out
- Publish the grading numbers in CRM once ready
- Assisting Martin with spreadsheet
- Improve plan for data to be taken into meetings

## Bedeho

- Make video about Network Performance Score, broadly. Not individual scores, but wider idea of how scoring works.

**Comment by bedeho** [comment]
Can you add a TODO item here to document this cadence in a graphic or something, also showing events like verifications, reports, plans, scoring data sampling, which can be placed on Gitbook?

**Comment by blrhc** [comment]
> TODO

Sure, who is it assigned to? I would guess yours truly?

**Comment by bedeho** [comment]
yourself

**Comment by blrhc** [comment]
# Meeting Date

Monday, 25th of April, 2022

# Participants

- Ben
- Bedeho
- Martin
- Tomato

# Agenda

- Going over status of todos from last meeting
- Discussion of grading progress
- Should these meetings be public?

# Conclusions

- This Monday meeting is now the sole weekly meeting for covering Incentives and Founding Member Program-related topics. There was not a final decision taken on inviting community members, but it does not seem a good idea to make these meetings public, since they will often need to make reference to specific community members.
- This Monday meeting will be focused on what went right or wrong in the preceding council term, and how that impacts the policy variables.
- We are now in the process of collecting the information/performing the spot-checks required for Period 5 (the current period).
- Period 4 grading will be finalised and published in the next few hours after the meeting finishes. New Founding Members and people who have reached the verification cap will be announced as soon as the scores are available.
- In general, the principle of not inducting people every week is very demotivating for participants, so we need to sort this out immediately.
- Marketing WG will not be getting JOY for now, but Martin has asked for easy-to-grade tasks. If these work, then the marketing working group can be re-implemented into the incentives scheme.

# Discussion points for next week

- Prospects of Ben and Martin taking over the AMA from Robert.
- Builders want a different payment arrangement from other testnet participants.
- General activity of staying in touch with the broader community in some away that solves communication issues

# TODO

## Martin 
- Getting the grading numbers out on Tuesday
- Writing guides for scripts used as part of grading process on Wednesday
- Further clarification of "who does what?" - this needs to be a granular weekly plan which covers all responsibilities under Incentives 3.0 on Wednesday
- Basic agenda for daily council meetings on Tuesday

## Ben
- Assist Martin with getting the grading numbers out
- Using template spreadsheet to create a format going forward
- Publish the grading numbers in CRM once ready
- Improve plan for data to be taken into meetings
- Improving metrics for areas of responsibility
- Understanding why the HR group has not made bounties
- Add verified status to CRM Person Explorer Dashboard
- Lots of other CRM improvements
- Design scheme whereby Founding Members can award pool of JOY to non-FMs each week
- Factor this scheme into CRM design

## Bedeho

- _nothing_

## Tomato

- _nothing_

**Comment by blrhc** [comment]
# Meeting Date

Monday, 2nd May, 2022

# Participants

- Ben
- Bedeho
- Martin
- Tomato

# Agenda

- Going over status of todos from last meeting
- Discussion of grading progress
- Setting new policy variable values (was not possible during meeting)
- Changing scoring metrics (was not possible during meeting)

# Conclusions

- Lack of granular weekly plan (Martin) and plan for data to be taken into meetings (Ben) made the meeting much less effective than it could have been.
- One important way of handling the granular responsibilities is having some sort of project management/tracking tool. We settled on using GitHub projects to track weekly and general tasks which are part of Incentives 3.0, though Tomato was in favour of using Notion.
- Some useful things which could be added to the data to be presented in every meeting include:
  - Runway for FM status based on role participation, i.e. how long do you have to work in a specific role to get FM status
  - Pie chart showing how much is being spent on each working group

# Discussion points (postponed to next week)

- Prospects of Ben and Martin taking over the AMA from Robert.
- Builders want a different payment arrangement from other testnet participants.
- Improving general activity of staying in touch with the broader community in some away that solves communication issues

# TODO

## Martin 
- Writing guides for scripts used as part of grading process by Wednesday
- Further clarification of "who does what?" - this needs to be a granular weekly plan which covers all responsibilities under Incentives 3.0 by Wednesday => to be partially handled by GitHub projects boards handling recurring and non-recurring tasks
- Improve plan for data to be taken into meetings (Ben and Martin to have call on this)

## Ben
- Publish latest grading numbers in CRM
- Improve plan for data to be taken into meetings (Ben and Martin to have call on this)
- Continue to make CRM improvements
- Announce scheme whereby Founding Members can award pool of JOY to non-FMs each week

## Bedeho

- _nothing_

## Tomato

- _nothing_

**Comment by bwhm** [comment]
# Meeting Date

Monday, 16th of May, 2022

# Participants

- Bedeho
- Martin
- Tomato

# Summary

- Grading not completed
- Martin presented a [draft of data](https://github.com/Joystream/marketing/issues/242) meant to be brought in to the meeting, for the purpose of evaluating/setting new council period parameters, scoring metrics and general improvements of the program
- Further discussions about the performance of individual working groups, the apparent lack of opportunities as stated by the Jsgenesis marketing team, and most of all - the Council

A recording of the meeting is available [here](https://play.joystream.org/video/26750).
