### ISSUE TITLE
Block explorer integrations

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#250]
# Background
We don't have a proper block explorer integration, and Pioneer does not offer the needed features for all the different purposes that explorers serve.

# Proposal
Complete integration with one or more of the major explorer providers

* [Subscan](https://www.subscan.io/) (supports Polkadot, Kusama, other mainnets, all the active parachains and many testnets)
* ~[Polkascan](https://polkascan.io/) (supports Polkadot and Kusama)~
* ~[Dotscanner](https://dotscanner.com/) (supports Polkadot and Kusama)~
* ~[Polkastats](https://polkastats.io/) (supports Polkadot and Kusama, has statistics on the networks)~

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202481905297589) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
Are we either:
1) Mainly concerned with a viable "other project" for visibility purposes
2) Actually getting block explorer functionality--even if this means in the short term deploying our own solution

Many options are open source, it just means that you make some sacrifices/investments:
1. Using their open source code (depending upon license) and customizing the implementation for our own use case. In such a case we would not only be providing incentives for self-hosting but also making use of the brain power available to craft the implementation and avoid using an external party to build this (forget the cost--none of them have any experience with our DAO, so they would be trying to understand and solve a puzzle without any idea of the end requirements in mind)
2. Having to invest in an external part instead of investing in our own community, which is a loss
3. Self-hosting means we lose initial visibility vs paying an external entity. But this is only `initially`--if our own community can customize an external solution for our specific needs, then it means that for them to adapt it the cost would be much lower.

**Comment by bedeho** [comment]
> Actually getting block explorer functionality

Yes this is the goal.

I don't know what you mean by deploying out own solution though, these are hosted services.

> Many options are open source, it just means that you make some sacrifices/investments:

What options are you referring to? The ones I listed? if so, that is news to me.

**Comment by mochet** [comment]
> > Actually getting block explorer functionality
> 
> Yes this is the goal.
> 
> I don't know what you mean by deploying out own solution though, these are hosted services.
> 
> > Many options are open source, it just means that you make some sacrifices/investments:
> 
> What options are you referring to? The ones I listed? if so, that is news to me.

I've not looked heavily into this, and I'm not a super technical person but from what I gather almost all of the projects you mentioned are all open source repos (either partially or fully) so my assumption is that they could be self hosted by our own community:
- https://github.com/subscan-explorer/subscan-essentials
- https://github.com/polkascan/explorer-ui
- https://github.com/Colm3na/polkastats-ng

Questions **I don't know** the answer to just yet are:
1. How much work does it require for our own community to create whatever code needs to be done in order to add "Joystream functionality"? (by this I refer to stuff like adding in all the extrinsics, and potentially adding other custom stuff like being able to understand our council, elections, proposal or forum modules)
2. Would these projects be receptive or even allow for our own community to code this and then have it merged onto their running block explorer websites?
3. Do these projects expect Joystream to provide funding for having it be listed (and perhaps there is some ongoing cost relating to the system/bandwidth resources it would utilize)?
