### ISSUE TITLE
Landing page: Update images for mobile view

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#278]
The bigger product screenshots don't really work on mobile, you get the same cropping problem as before. We should find different view for these views, perhaps just picking one of the floating components or something.

**Comment by dmtrjsg** [comment]
@toiletgranny @kdembler

**Comment by toiletgranny** [comment]
Started digging into this, and I'd say we're looking at around 3 hours of design work and probably a similar implementation time. @dmtrjsg should I take care of this one, before I jump back into Atlas issues for this week?

**Comment by dmtrjsg** [comment]
@toiletgranny please feel free

**Comment by kdembler** [comment]
Also once new images are done let's address these point from #279 here (if still applicable):

- [ ] Fix vertical margin between quote section and NFT section.
- [ ] Fix corner artefact on Pioneer screenshot. Should be transparent or on top of background same as on landing page, looks bad now.
- [ ] Make sure images have @2x variant available (or are just in high-res)
- [ ] Optimize images for web, use modern format and make sure they are small in size

**Comment by toiletgranny** [comment]
@bedeho @dmtrjsg Here's a mobile prototype of the JS.org homepage with a new take on mobile illustrations. https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=5719%3A219138&node-id=6395%3A306806&viewport=1153%2C529%2C0.05&scaling=min-zoom

Here's what changed:

1. For the hero illustration, I made it slightly larger to take advantage of the horizontal space. However, I'd recommend not to crop it after all, as no cropping did a good job at explaining the context, meaning: it's a video platform and this is a video page. It's a good moment to point out that a similar approach can be seen in the majority of the benchmarks you Bedeho provided, here are some examples that you can preview on mobile:
    - https://radicle.xyz/
    - https://github.com/features/codespaces
    - https://ghost.org/
2. For Payouts, Video NFTs, Creator Tokens, and  — in the future —Youtube Sync sections, I made all illustrations larger and cropped them in a way that focuses on the critical part of each of them. With this approach, I'm hoping to make the implementation more straightforward and easier to manage in the future.
3. For the secondary illustrations in the Payouts section, I stretched them so that they go from edge to edge of the viewport.

@kdembler Let me know when you have a moment to sync and talk about implementing these changes.
